### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by bogas04** [bogas04/SikhJS#104]
It's very hard to maintain a project which doesn't have any contributors or users (lol).

Plan for rewriting one module at a time, one build step at a time:

### Phase 1

* [x] Use `xo` for linting
* [x] Remove dependencies:
  * [x] `react-mdl`: Why ? It's good for prototypes but not for my use-case. I need to custom build the UI.
  * [x] `react-throttle`: I don't even know if it's helping at all.
  * [x] `ws`: With webpack 2, we can also use its server for dev testing.
  * [x] `react-calendar`: very fat and not a major feature.
* [x] Update/Replace dependencies;
  * [x] Upgrade to webpack 2. It's simple change that might help in reducing some bundle size.
  * [x] Upgrade to react-router v4.
  * [x] Consider using preact over react. We can definitely benefit with a smaller bundle size.
    * Considered, but waiting for react@16 to go gold.
* [x] New dependencies:
  * [x] Consider glamor / styled-jsx for CSS.
    * Using `styled-components` instead.

### Phase 2

* [x] Perf
  * [x] Code Split vendor and app-code
  * [x] Find more areas to split code based on route or component. #112
  * [x] Use Service Worker to cache vendor.min.js, app.min.js and other assets.
  * [x] Prefetch angs etc. #112

* [x] Cleanup
  * [x] Fix xo lint errors.
  * [x] Re-org components into components and pages, so that we have a clear distinction between those.
  * [x] Redux? 
    * Our actions are fairly less, and the state is mingled much, so I'm not sure if we really require redux as of now.
    * On a second thought, having redux store will help us make the app offline-first more readily.
  * [x] push to location for `sggs`, `shabads` etc on ang/query change.

* [x] Features
  * [x] Use `react-router-dom` in much more ergonomic way instead of simply porting RR3 to RR4.
  * [x] Style all the things!
    * [x] Improve navigation. I want it to work the way user uses the app and not how the sitemap looks like. Search and Sehaj paath being the main features. We can try interactions like floating icons or tabs ?
    * [x] Use some cleaner react-calendar alternative (make yourself!) - #105

**Comment by bogas04** [comment]
I would really love a friend who can motivate me to work on this 🙈

**Comment by bogas04** [comment]
rewrite does master reorg and dependency changes.

It uses:

* webpack2
* babel-preset-env
* react-router-dom (v4)
* styled-components
* snarkdown over remarkable (very lightweight markdown parser)

And doesn't use:

* react-calendar
* react-router (v3)
* react-mdl

We've lost the styles and polished look, but we have more flexibility in hand now !

Our bundle size is already [down to](https://github.com/bogas04/SikhJS/blob/982de6800371ae4439d31551bdcea2867be26e5e/assets/js/bundle.js) 400-ish kbs [from](https://github.com/bogas04/SikhJS/blob/e2ee95e6fc04085bae9fb3fca77d57b1eb6dc247/bundle.js) 900-ish kbs! Of course it isn't fair to compare as we don't yet have calendar in place, but we can now employ code splitting for more perf benefits! 

I tried using preact over react, but seeing how React is gonna change a lot with 16 (Fiber), I think it'll be better to stick around with react for a while. For reference, it brought bundle size by around 100kbs. Also, react@next as of 15 March 2017 actually increases the bundle size by 10kb or so. But I guess it's a minor trade-off for general perf improvements.

Also, the production webpack build is made by simply using `webpack -p` and no special plugins as such. Using those might help us reduce bundle size further down.

**Comment by perminder-klair** [comment]
@bogas04 good job bro! I am happy to help you in this project, let me know which area you want me to have a look.

**Comment by bogas04** [comment]
Thank you so much @perminder-klair !! You can take time to get used to the app, get it building on your system and then I can help you in finding issues that you can take up.

I'm really sorry for late reply, have been very busy lately.

**Comment by perminder-klair** [comment]
@bogas04 I got it all setup already, all looks good!

**Comment by bogas04** [comment]
That's great @perminder-klair . You could take up some of these issues:

* #100 
* #89 
* #83
* #54
* #50 (I suck at design as you might have guessed already)
* #49
* #25

These are some easy first-pr issues. Really sorry for late replies, have been very busy lately. I can't thank you enough for sticking around and trying to help this projec.t

**Comment by bogas04** [comment]
Added redux support for two actions

* [x] toggleNightMode
* [x] increaseFontSize
* [x] decreaseFontSize
* [ ] setAng
* [ ] increaseAng
* [ ] decreaseAng

**Comment by bogas04** [comment]
Closing as most of the work is done. Remaining parts can be covered by individual issues.
