### ISSUE TITLE
Remove code smell

### ISSUE THREAD

**Issue by bogas04** [bogas04/SikhJS#59]
As the web app is moving towards complex features, components are starting to smell a lot and `actions` are coming up in the components.

I guess it's about time we use Flux sort of architecture to reduce code smell. 
- [ ] See which methodology would suit SikhJS (MobX, Redux, ???)
  - [ ] Segregate `actions`
  - [x] Use stateless components unless really required
  - [ ] Implement the architecture 
  - [ ] Integrate with IDB / FireBase (see #20 ) 
- [x] Refactor Components to use as little logic as possible
  - [x] Rely more on HOC to abstract logic into more re-usable components.
  - [x] Move to react-mdl #52 
  - [x] Switch to React Router 4 #44

**Comment by bogas04** [comment]
**MERGED** react-mdl branch is going well:
- Uses HOC for Loader and Toolbar. We can even do something similar for SearchCards.
- Lost 23% worth of size in bundle by switching to react-mdl

**Comment by bogas04** [comment]
637acf3b060c0d6c11a30871ee4b36611bd44a21 uses function as children concepts for components like Fetch -> Markdown, Json -> GurbaniNow. This way we keep the fetching part primarily in Fetch.

Later we can implement caches at that level for better perf.

**Comment by bogas04** [comment]
#104 `rewrite` branch deals with it. Should ship with 0.6.0
