### ISSUE TITLE
Add meta description

### ISSUE THREAD

**Issue by bogas04** [bogas04/SikhJS#89]
* [ ] Initially we can simply add some desc of the project and nishaan
* [ ] As we progress, we can collect meta data from current route;
  * [ ] Rahao pangti of current Shabad (Depends on #83)
  * [ ] Shabad results 
  * [ ] Author Page
  * [ ] Raag Page
  * [ ] SGGS Ang
  * [ ] Nitnem Details

**Comment by bogas04** [comment]
Thanks to 36a5e9e2aef48659e76f3c55c1006103f098ca34, we now add titles based on routes. 

We can extend it further to add meta data next.
